# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization
    label: Organization
    datajson: publisher.name
  - field_name: notes
    label: Description
    datajson: description
  - field_name: license
    label: License
    datajson: license
  - field_name: category
    label: Category
    display_template: display/category.html
    datajson: category
  - field_name: maintainer
    label: Maintainer
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Maintainer Email
    datajson: contactPoint.hasEmail
  - field_name: doi
    label: DOI
    datajson: identifier
  - field_name: citation
    label: Citation

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: doi
    label: DOI
    datajson: description
  - field_name: format
    label: Format
    datajson: distribution.format
    values:
      - api
      - csv
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - zip
      - nc
      - tiff

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
